dist: xenial
#language: cpp
language: python
python: "3.7"
compiler: clang

# Install conan
install:
  - pip3 install conan
  # Automatic detection of your arch, compiler, etc.
  - conan user

# install and set g++-8 and boost
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libboost-test-dev
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
before_install:
    - eval "${MATRIX_EVAL}"
    - sudo update-alternatives --remove-all g++
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 60
    - sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 60
    - sudo update-alternatives --set c++ /usr/bin/g++
    - sudo update-alternatives --config g++


# run  
script:
- conan install .
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 60
- conan profile update settings.compiler.libcxx=libstdc++11 default
- conan profile update settings.compiler.version=8 default   
- conan install .
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
