dist: xenial
language: cpp
compiler: clang
# safelist
branches:
  only:
  - master

# install and set g++-8 and boost
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://archive.ubuntu.com/ubuntu xenial main universe'
          packages:
            - g++-8
            - libopenblas-dev
            - libdlib-dev
          update: true
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
before_install:
    - eval "${MATRIX_EVAL}"
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 60

# run  
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
