dist: xenial
language: python
python: "3.7"
compiler: clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8
    - libboost-test-dev
install:
# Install conan
  - pip install conan
  # Automatic detection of your arch, compiler, etc.
  - conan user
script:
- g++ --version
- conan install .
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
