dist: xenial
language: cpp
python: "3.7"
compiler: clang
install:
# Install conan
  - pip install conan
  # Automatic detection of your arch, compiler, etc.
  - conan user
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8
    - libboost-test-dev
script:
- conan install .
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package