dist: eoan
language: cpp
compiler: clang
# safelist
branches:
  only:
  - master

# install and set g++-8 and boost
addons: 
    apt: #
        update: true # analog for before_install: sudo apt-get update 
        sources:
        - ubuntu-toolchain-r-test 
        packages:
        - libboost-test-dev
        - libopencv-dev

# run
script:
- mkdir release
- cd release/
- cmake ..
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package

